name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black (code format check)
        run: black --check .

      - name: Run Flake8 (style/lint check)
        run: flake8 .

      - name: Run Pytest (unit tests)
        run: pytest --maxfail=1 --disable-warnings -q
